apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: jws-stateful-app
    name: jws-stateful-app
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: jws-stateful-app
    name: jws-stateful-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jws-stateful-app:latest
    postCommit: {}
    resources: {}
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-webserver56-openjdk11-tomcat9-openshift-ubi8:latest
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: U08MaZrMLS-Szrfne5P6
      type: GitHub
    - generic:
        secret: F2oOKXqwOXV9UwLyo5-j
      type: Generic
  status:
    lastVersion: 0
kind: List
metadata: {}
